# Generated by Django 5.0.6 on 2024-06-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
